services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cmms-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    env_file:
      - .env
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    networks:
      - cmms-network

  nginx:
    image: nginx:alpine
    container_name: cmms-nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - cmms-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    command: supervisord -c /etc/supervisor/conf.d/supervisord.conf
    env_file:
      - .env
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    networks:
      - cmms-network
    deploy:
      replicas: 3

  redis:
    image: redis:7-alpine
    container_name: cmms-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - cmms-network

volumes:
  redis_data:

networks:
  cmms-network:
    driver: bridge
