version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cmms-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - app-storage:/var/www/html/storage
      - app-vendor:/var/www/html/vendor
      - app-node_modules:/var/www/html/node_modules
      - /var/www/html/node_modules
      - /var/www/html/vendor
    ports:
      - '8000:80'
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=103.152.5.77
      - DB_PORT=3309
      - DB_DATABASE=cmms
      - DB_USERNAME=cmms
      - DB_PASSWORD=cmmstekpol@2025
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80/up', '||', 'exit', '1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cmms-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: cmms-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cmms-network

  # Node.js for development (separate container for hot reloading)
  node:
    image: node:20-alpine
    container_name: cmms-node
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
      - app-node_modules:/app/node_modules
    ports:
      - '5173:5173'
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - NODE_ENV=development
    networks:
      - cmms-network

  # Mailhog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: cmms-mailhog
    restart: unless-stopped
    ports:
      - '1025:1025' # SMTP
      - '8025:8025' # Web UI
    networks:
      - cmms-network

# Named volumes for persistent data
volumes:
  redis-data:
    driver: local
  app-storage:
    driver: local
  app-vendor:
    driver: local
  app-node_modules:
    driver: local

# Custom network
networks:
  cmms-network:
    driver: bridge
