services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cmms-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - storage_data:/var/www/html/storage
      - cache_data:/var/www/html/bootstrap/cache
    env_file:
      - .env
    networks:
      - cmms-network
    command: ['/usr/local/bin/set-permissions.sh', 'php-fpm']

  nginx:
    image: nginx:alpine
    container_name: cmms-nginx
    restart: unless-stopped
    ports:
      - '8081:8081'
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - cmms-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - storage_data:/var/www/html/storage
      - cache_data:/var/www/html/bootstrap/cache
    command:
      [
        '/usr/local/bin/set-permissions.sh',
        'supervisord',
        '-c',
        '/etc/supervisor/conf.d/supervisord.conf',
      ]
    env_file:
      - .env
    networks:
      - cmms-network
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  redis:
    image: redis:7-alpine
    container_name: cmms-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - cmms-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

volumes:
  redis_data:
  storage_data:
  cache_data:

networks:
  cmms-network:
    driver: bridge
